data: '/home/siyi/project/PCL/data/hg'
arch: 'resnet50'
workers: 4
epochs: 300
start_epoch: 0
batch_size: 4
lr: 0.03
schedule: []
momentum: 0.9
weight_decay: 1e-4
print_freq: 10
resume: ''
world_size: 1
rank: 0
dist_url: 'tcp://localhost:10002'
dist_backend: 'nccl'
seed: 0
gpu: 0
multiprocessing_distributed: True
low_dim: 128
pcl_r: 4
moco_m: 0.999
temperature: 0.2
mlp: True
aug_plus: True
cos: True
#num_cluster: '8,9,10'
num_cluster: '8,9'
warmup_epoch: 0
exp_dir: 'exp/'
